# Generated by Django 5.2.8 on 2025-12-02 16:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('name_of_owner', models.CharField(blank=True, max_length=255)),
                ('rented', models.BooleanField(default=False)),
                ('since', models.DateField(blank=True, null=True)),
                ('complete_address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('preferred_mop', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('DAYS_30', '30 days'), ('DAYS_60', '60 days'), ('DAYS_90', '90 days'), ('CONSIGN', 'Consignment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.CharField(help_text='Format: C-YYYY-XXXX (e.g., C-2025-0001).', max_length=20, unique=True)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('to', models.CharField(help_text='Recipient name (usually client contact).', max_length=255)),
                ('address', models.TextField(help_text='Recipient address, usually the client address.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_number', models.CharField(help_text='Format: YYYY-XXXX (e.g., 2025-0001). Generated by system.', max_length=20, unique=True)),
                ('date_of_order', models.DateField(default=django.utils.timezone.now)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('NEW_DR', 'New DR'), ('FOR_DELIVERY', 'For Delivery'), ('DELIVERED', 'Delivered')], default='NEW_DR', max_length=20)),
                ('payment_status', models.CharField(choices=[('NA', 'N/A'), ('FOR_COUNTER_CREATION', 'For Counter Creation'), ('FOR_COUNTERING', 'For Countering'), ('COUNTERED', 'Countered'), ('FOR_COLLECTION', 'For Collection'), ('FOR_DEPOSIT', 'For Deposit'), ('DEPOSITED', 'Deposited')], default='NA', max_length=30)),
                ('delivery_method', models.CharField(choices=[('DELIVERY', 'Delivery'), ('DOOR_TO_DOOR', 'Door to Door')], default='DELIVERY', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('DAYS_30', '30 days'), ('DAYS_60', '60 days'), ('DAYS_90', '90 days'), ('CONSIGN', 'Consignment')], max_length=20)),
                ('payment_details', models.TextField(blank=True, help_text='Used for notes on partial payments, terms, deposit details, etc.')),
                ('payment_due', models.DateField(blank=True, help_text='Financial due date if needed (separate from delivery due_date).', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_delivery_receipts', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipts', to='bondking_app.client')),
                ('counter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_receipt', to='bondking_app.counter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceiptUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('system_update', models.TextField(help_text='Auto-generated summary, e.g. `[MM/DD/YYYY] User X changed payment_status from A to B`.')),
                ('user_notes', models.TextField(blank=True)),
                ('delivery_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='bondking_app.deliveryreceipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipt_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField()),
                ('issuance_type', models.CharField(choices=[('TF_WH', 'TF to WH'), ('WH_HQ', 'WH to HQ'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_issuances', to=settings.AUTH_USER_MODEL)),
                ('dr', models.ForeignKey(blank=True, help_text='Linked when issuance comes from a DR (Delivered).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issuances', to='bondking_app.deliveryreceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_issuances', to='bondking_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Defaults to product name; user can add more details.', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('delivery_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bondking_app.deliveryreceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipt_items', to='bondking_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_to', models.CharField(help_text='Supplier name', max_length=255)),
                ('address', models.TextField(help_text='Supplier address')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('RFP_CREATED', 'RFP Created'), ('RFP_APPROVED', 'RFP Approved'), ('PO_CREATED', 'PO Created'), ('PO_APPROVED', 'PO Approved'), ('CHEQUE_CREATED', 'Cheque Created'), ('CHEQUE_SIGNED', 'Cheque Signed'), ('PAYMENT_RELEASED', 'Payment Released'), ('FILED', 'Filed')], default='RFP_CREATED', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Usually Top Management', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, help_text='Usually Accounting Head', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='bondking_app.purchaseorder')),
            ],
        ),
    ]
