# Generated by Django 5.2.8 on 2025-12-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryissuance',
            name='remarks',
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
