# Generated by Django 5.2.8 on 2025-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0002_remove_inventoryissuance_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreceipt',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
