# Generated by Django 5.2.8 on 2025-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0003_deliveryreceipt_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='since',
            field=models.CharField(blank=True, help_text='Year since the client started, e.g., 2015', max_length=4, null=True),
        ),
    ]
