# Generated by Django 5.2.8 on 2025-12-14 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0004_alter_client_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreceipt',
            name='source_dr',
            field=models.ForeignKey(blank=True, help_text='Required only for Door to Door DRs. Must reference an HQ Stocks DR (not archived).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='door_to_door_children', to='bondking_app.deliveryreceipt'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='delivery_method',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('HQ_STOCKS', 'HQ Stocks'), ('DOOR_TO_DOOR', 'Door to Door')], default='DELIVERY', max_length=20),
        ),
    ]
