# Generated by Django 5.2.8 on 2025-12-14 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0005_deliveryreceipt_source_dr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('REQUEST_FOR_PAYMENT', 'Request for Payment'), ('PURCHASE_ORDER', 'Purchase Order'), ('CHECK_CREATION', 'Check Creation'), ('CHECK_SIGNING', 'Check Signing'), ('PAYMENT_RELEASE', 'Payment Release'), ('PO_FILING', 'PO Filing'), ('ARCHIVED', 'Archived')], default='REQUEST_FOR_PAYMENT', max_length=30),
        ),
        migrations.CreateModel(
            name='PurchaseOrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('system_update', models.TextField()),
                ('user_notes', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='bondking_app.purchaseorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
