# Generated by Django 5.2.8 on 2025-12-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0006_purchaseorder_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, help_text='Format: YYYY-XXXX. Auto-generated when PO reaches Purchase Order stage.', max_length=20, unique=True),
        ),
    ]
