# Generated by Django 5.2.8 on 2025-12-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0007_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreceipt',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
