# Generated by Django 5.2.8 on 2025-12-16 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0008_deliveryreceipt_is_cancelled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryissuance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inventoryissuance',
            name='dr',
        ),
        migrations.RemoveField(
            model_name='inventoryissuance',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryissuance',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryissuance',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryissuance',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryissuance',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventoryissuance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryissuance',
            name='issuance_type',
            field=models.CharField(choices=[('TF_TO_WH', 'TF → WH'), ('WH_TO_HQ', 'WH → HQ')], max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryIssuanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('issuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bondking_app.inventoryissuance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bondking_app.product')),
            ],
        ),
    ]
