# Generated by Django 5.2.8 on 2025-12-19 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0009_remove_inventoryissuance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='delivery_method',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('D2D_STOCKS', 'D2D Stocks'), ('DOOR_TO_DOOR', 'Door to Door')], default='DELIVERY', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='source_dr',
            field=models.ForeignKey(blank=True, help_text='Required only for Door to Door DRs. Must reference an D2D Stocks DR (not archived).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='door_to_door_children', to='bondking_app.deliveryreceipt'),
        ),
    ]
