# Generated by Django 5.2.8 on 2025-12-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0010_alter_deliveryreceipt_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
