# Generated by Django 5.2.8 on 2025-12-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0012_productid_purchaseorder_product_id_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='rfq_number',
            new_name='rfp_number',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('REQUEST_FOR_PAYMENT', 'Request for Payment'), ('REQUEST_FOR_PAYMENT_APPROVAL', 'Request for Payment (Approval)'), ('PURCHASE_ORDER', 'Purchase Order'), ('PURCHASE_ORDER_APPROVAL', 'Purchase Order (Approval)'), ('CHECK_CREATION', 'Check Creation'), ('CHECK_SIGNING', 'Check Signing'), ('PAYMENT_RELEASE', 'Payment Release'), ('PO_FILING', 'PO Filing'), ('ARCHIVED', 'Archived')], default='REQUEST_FOR_PAYMENT', max_length=30),
        ),
    ]
