# Generated by Django 5.2.8 on 2025-12-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0013_rename_rfq_number_purchaseorder_rfp_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='complete_address',
        ),
        migrations.AddField(
            model_name='client',
            name='barangay',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='city_municipality',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='province_state',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='street_number',
            field=models.CharField(blank=True, help_text='House or building number', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='unit_room',
            field=models.CharField(blank=True, help_text='Unit, room, floor, or apartment number', max_length=50),
        ),
    ]
