# Generated by Django 5.2.8 on 2025-12-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0014_remove_client_city_remove_client_complete_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreceipt',
            name='deposit_slip_no',
            field=models.CharField(blank=True, help_text='Required before deposit completion', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='proof_of_delivery',
            field=models.ImageField(blank=True, help_text='Uploaded upon delivery', null=True, upload_to='proof_of_delivery/'),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='sales_invoice_no',
            field=models.CharField(blank=True, help_text='Optional sales invoice reference', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='barangay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_number',
            field=models.CharField(help_text='House or building number', max_length=50),
        ),
    ]
