# Generated by Django 5.2.8 on 2025-12-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0015_deliveryreceipt_deposit_slip_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='preferred_mop',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('DAYS_15', '15 days'), ('DAYS_30', '30 days'), ('DAYS_60', '60 days'), ('DAYS_90', '90 days'), ('DAYS_120', '120 days')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DAYS_15', '15 days'), ('DAYS_30', '30 days'), ('DAYS_60', '60 days'), ('DAYS_90', '90 days'), ('DAYS_120', '120 days')], max_length=20),
        ),
    ]
