# Generated by Django 5.2.8 on 2025-12-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0016_alter_client_preferred_mop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='counter',
        ),
    ]
