# Generated by Django 5.2.8 on 2026-01-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0017_remove_deliveryreceipt_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='street_number',
            field=models.CharField(help_text='House or building number', max_length=150),
        ),
    ]
