# Generated by Django 5.2.8 on 2026-01-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0018_alter_client_street_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderparticular',
            name='particular',
            field=models.CharField(max_length=500),
        ),
    ]
