# Generated by Django 5.2.8 on 2026-01-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0019_alter_purchaseorderparticular_particular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='delivery_method',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('D2D_STOCKS', 'D2D Stocks'), ('DOOR_TO_DOOR', 'Door to Door'), ('SAMPLE', 'Sample')], default='DELIVERY', max_length=20),
        ),
    ]
