# Generated by Django 5.2.8 on 2026-01-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0021_client_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreceipt',
            name='reject_problem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='reject_solution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
