# Generated by Django 5.2.8 on 2026-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0022_deliveryreceipt_reject_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='barangay',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_number',
            field=models.CharField(blank=True, help_text='House or building number', max_length=150),
        ),
    ]
