# Generated by Django 5.2.8 on 2026-01-12 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0023_alter_client_barangay_alter_client_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryissuance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
