# Generated by Django 5.2.8 on 2026-01-14 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0024_inventoryissuance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('REQUEST_FOR_PAYMENT', 'Request for Payment'), ('REQUEST_FOR_PAYMENT_APPROVAL', 'Request for Payment (Approval)'), ('PURCHASE_ORDER', 'Purchase Order'), ('PURCHASE_ORDER_APPROVAL', 'Purchase Order (Approval)'), ('BILLING', 'Billing'), ('PO_FILING', 'PO Filing'), ('ARCHIVED', 'Archived')], default='REQUEST_FOR_PAYMENT', max_length=30),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_number', models.CharField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CHECK_CREATION', 'Check Creation'), ('CHECK_SIGNING', 'Check Signing'), ('PAYMENT_RELEASE', 'Payment Release'), ('PAID', 'Paid')], default='CHECK_CREATION', max_length=30)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('source_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='bondking_app.purchaseorder')),
            ],
        ),
    ]
