# Generated by Django 5.2.8 on 2026-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0025_alter_purchaseorder_cheque_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_number',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
