# Generated by Django 5.2.8 on 2026-01-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0026_alter_billing_billing_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_number',
            field=models.CharField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
