# Generated by Django 5.2.8 on 2026-01-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0027_alter_billing_billing_number'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE bondking_app_purchaseorder
            SET status = 'PURCHASE_ORDER_CREATION'
            WHERE status IN (
                'REQUEST_FOR_PAYMENT',
                'REQUEST_FOR_PAYMENT_APPROVAL',
                'PURCHASE_ORDER'
            );
            """
        )
    ]

