# Generated by Django 5.2.8 on 2026-01-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0028_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rfp_number',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PURCHASE_ORDER_CREATION', 'Purchase Order Creation'), ('PURCHASE_ORDER_APPROVAL', 'Purchase Order Approval'), ('BILLING', 'Billing'), ('PO_FILING', 'PO Filing'), ('ARCHIVED', 'Archived')], default='PURCHASE_ORDER_CREATION', max_length=30),
        ),
    ]
