# Generated by Django 5.2.8 on 2026-01-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondking_app', '0029_remove_purchaseorder_rfp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='billing/proof_of_payment/'),
        ),
    ]
